### ISSUE TITLE
ast parse error; sret paramter attribute

### ISSUE THREAD

**Issue by pupiles** [llir/ll#7]
Hi,
`define void @testcase_1dep.Foo.Bar({ { i8*, i64 }, { i8*, i64 } }* nocapture sret({ { i8*, i64 }, { i8*, i64 } }) %sret.formal.0, i8* nest nocapture readnone %nest.0, %Foo.0* readnone %f, i8* %command.chunk0, i64 %command.chunk1) #0 !dbg !6 {
entry:
  %tmp.0 = alloca { { i8*, i64 }, { i8*, i64 } }, align 8
  %tmpv.0 = alloca [2 x { i8*, i64 }], align 8
  %tmpv.1 = alloca { { i8*, i64 }, { i8*, i64 } }, align 8
  call void @llvm.dbg.value(metadata %Foo.0* %f, metadata !28, metadata !DIExpression()), !dbg !29
  call void @llvm.dbg.value(metadata i8* %command.chunk0, metadata !30, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 64)), !dbg !29
  call void @llvm.dbg.value(metadata i64 %command.chunk1, metadata !30, metadata !DIExpression(DW_OP_LLVM_fragment, 64, 64)), !dbg !29
  %cast.38 = bitcast [2 x { i8*, i64 }]* %tmpv.0 to i8*, !dbg !31
  call void @llvm.memcpy.p0i8.p0i8.i64(i8* noundef nonnull align 8 dereferenceable(16) %cast.38, i8* noundef nonnull align 8 dereferenceable(16) bitcast ({ i8*, i64 }* @const.16 to i8*), i64 16, i1 false), !dbg !31
  %command.addr.sroa.0.0.cast.39.sroa_idx = getelementptr inbounds [2 x { i8*, i64 }], [2 x { i8*, i64 }]* %tmpv.0, i64 0, i64 1, i32 0, !dbg !31
  store i8* %command.chunk0, i8** %command.addr.sroa.0.0.cast.39.sroa_idx, align 8, !dbg !31
  %command.addr.sroa.4.0.cast.39.sroa_idx4 = getelementptr inbounds [2 x { i8*, i64 }], [2 x { i8*, i64 }]* %tmpv.0, i64 0, i64 1, i32 1, !dbg !31
  store i64 %command.chunk1, i64* %command.addr.sroa.4.0.cast.39.sroa_idx4, align 8, !dbg !31
  %call.0 = call { i8*, i64 } @runtime.concatstrings(i8* nest undef, i8* null, i8* nonnull %cast.38, i64 2), !dbg !31
  call void @llvm.dbg.value(metadata i8* undef, metadata !30, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 64)), !dbg !29
  call void @llvm.dbg.value(metadata i64 undef, metadata !30, metadata !DIExpression(DW_OP_LLVM_fragment, 64, 64)), !dbg !29
  %icmp.0 = icmp eq %Foo.0* %f, null, !dbg !32
  br i1 %icmp.0, label %then.0, label %else.0, !make.implicit !5`
the parse deal this the part of llvm ir file will throw error
`unable to parse "/Users/admin/test/test.ll" into an AST: syntax error at line 1`
debug value as follow
state: 614
action: -2

**Comment by pupiles** [comment]
may be i should create this issue at https://github.com/inspirer/textmapper

**Comment by mewmew** [comment]
Hi @pupiles,

Could you upload the full source code of the `test.ll` file? I think you can just drag and drop it into the GitHub issue comment, to upload.

It seems the source code you wrote in quotes is truncated.

Running the same code that you uploaded through the official LLVM tools gives the following error:

```
$ lli test.ll
lli: test.ll:1:82: error: expected ')' at end of argument list
define void @testcase_1dep.Foo.Bar({ { i8*, i64 }, { i8*, i64 } ....... %else.0, !make.implicit !5
```

So it seems some of the LLVM IR code is missing.

Cheers,
Robin

**Comment by pupiles** [comment]
Hi Robin,
Thanks for reply, 
there is the full file
[test.zip](https://github.com/llir/ll/files/6478243/test.zip)
i got it from [gollvm](https://go.googlesource.com/gollvm/) and just one file from a go project,so there is no main function in it.if you need more info,i can provide whole project .ll file.

**Comment by mewmew** [comment]
Thanks for uploading the file @pupiles. It looks like that file is not updated to the latest syntax of LLVM, since the official LLVM tools do not successfully parse it.

``` 
$ lli lli test.ll
lli: test.ll:141:82: error: expected ')' at end of argument list
define void @testcase_1dep.Foo.Bar({ { i8*, i64 }, { i8*, i64 } }* nocapture sret({ { i8*, i64 }, { i8*, i64 } }) %sret.formal.0, i8* nest nocapture readnone %nest.0, %Foo.0* readnone %f, i8* %command.chunk0, i64 %command.chunk1) #0 !dbg !6 {
                                                                                 ^
```

This is using LLVM version 11.1.0.

So, perhaps `test.ll` is a bad example, since the official LLVM tools do not support it.

Cheers,
Robin

**Comment by mewmew** [comment]
If you remove `sret(...)` from two places in `test.ll`, then `llir/llvm/cmd/l-tm` parses the grammar successfully. ~However, it fails with `noundef` enum not defined. If removing the `noundef` function attribute, then the file parses successfully.~

Uploading an example:
[test.zip](https://github.com/llir/ll/files/6478482/test.zip)

~@dannypsnl do you know if the `noundef` function attribute was added (or removed) in LLVM 11.0?~

**Comment by pupiles** [comment]
`$ lli-12 -version
LLVM (http://llvm.org/):
  LLVM version 12.0.0
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: cascadelake`

My local env is llvm-12 and lli seems not syntax error,so llir not support llvm12 yet?
`$ lli-12 test.ll
lli-12: error: 'main' function not found in module.`

For noundef error i edit _ParamAttr* var from paramattr_string2enum.go seems work

**Comment by mewmew** [comment]
> My local env is llvm-12 and lli seems not syntax error,so llir not support llvm12 yet?

Exactly, llir does not yet support LLVM 12.0, this is tracked by llir/llvm#169. The llir project supports LLVM 11.0, thanks to the work of @dannypsnl in llir/llvm#147.

> For noundef error i edit _ParamAttr* var from paramattr_string2enum.go seems work

Thanks. The `noundef` issue has now been fixed (rev llir/llvm@5ea92e1009ccbe5332b134468fce0c9cad844057).

**Comment by pupiles** [comment]
OK, looking forward to it!Thanks for you guys work!

**Comment by mewmew** [comment]
Tracked by llir/llvm#169. Closing this issue to keep tracking in one place.
