### ISSUE TITLE
ast parse error; sret paramter attribute

### ISSUE THREAD

**Issue by pupiles** [llir/ll#8]
Hi,
i test other .ll file by remove the sret() attr,but some of them still throw errors
[test1.zip](https://github.com/llir/ll/files/6488792/test1.zip)
may be these are not the features of llvm12?

**Comment by mewmew** [comment]
>  may be these are not the features of llvm12?

Yeah, I think this was introduced in LLVM 12.

ref: https://github.com/llir/llvm/blob/9cc56640dd8f366c6aa61ed01496f2dc18f1b90f/llvm12.diff#L1063

```diff
+    case lltok::kw_sret: {
+      Type *Ty;
+      if (parseRequiredTypeAttr(Ty, lltok::kw_sret))
+        return true;
+      B.addStructRetAttr(Ty);
+      continue;
+    }
```

**Comment by mewmew** [comment]
@pupiles, for the future, please create [issues](https://github.com/llir/llvm/issues) on the [llir/llvm](https://github.com/llir/llvm) repository. We try to track all issues related to `llir` in the `llir/llvm` repo, so we can add labels and track them collectively.

Cheers,
Robin

**Comment by pupiles** [comment]
Yeah, the sret attr is the feature in llvm 12, so i remove the sret attr in my .ll file ,i mean the file in test1.zip occurs error seems not llvm 12 features.
thanks for your suggestion,i will create issues in llir/llvm later.

**Comment by mewmew** [comment]
> i mean the file in test1.zip occurs error seems not llvm 12 features.

If so, please report the errors (that are not LLVM 12 features), so we can fix them :)

**Comment by mewmew** [comment]
Tracked by llir/llvm#169. Closing this issue to keep tracking in one place.
