### ISSUE TITLE
Can you provide an example of how to use it?

### ISSUE THREAD

**Issue by monkbai** [llir/ll#9]
Can you provide an example of how to use the lexers and parsers generated for LLVM IR assembly in this project?

**Comment by mewmew** [comment]
Hi @monkbai,

Glad you are showing an interest in LLVM IR parsing! The `https://github.com/llir/ll` package is considered a very low-level package, and for most users, we'd recommend using e.g. [github.com/llir/llvm/asm.ParseFile](https://pkg.go.dev/github.com/llir/llvm/asm#ParseFile) to parse LLVM IR assembly files.

However, if you wish to get into the nitty gritty low-level details, then take a look at the lexer and parser generator project [Textmapper](https://github.com/inspirer/textmapper) by @inspirer. Also, take a look at the Textmapper web page which has a lot of good documentation: https://textmapper.org/

For code using the lexer and parser for LLVM IR generated by Textmapper, see for example [github.com/llir/llvm/asm/asm.go](https://github.com/llir/llvm/blob/f8d0325a931a3e5b286f6d92ac95d11c5856da23/asm/asm.go#L53):
```go
import "github.com/llir/ll/ast"

func ParseString(path, content string) (*ir.Module, error) {
	parseStart := time.Now()
	tree, err := ast.Parse(path, content)
	if err != nil {
		return nil, errors.Wrapf(err, "unable to parse %q into an AST", path)
	}
	dbg.Println("parsing into AST took:", time.Since(parseStart))
	root := ast.ToLlvmNode(tree.Root())
	return translate(root.(*ast.Module))
}
```

Wish you happy coding!

Cheers,
Robin

**Comment by mewmew** [comment]
Closing this issue for now, feel free to re-open if you want to discuss other aspects of lexing/parsing, or if something is unclear.

Cheers,
Robin
